travis:
  secure:
    BINSTAR_TOKEN: wT8triW5YJQdXU94+XtzKBrA1pxkKJjeZd6oWPczaVZen38IAJyr03ES0P0snwuX5VRyW67l4IeUmZIuRmuzeDvYuUuMEO0RiHzslBjXTUgexs3NJ9OFIVCXE+RPkvkTgzGoRx6yw4DwdHYlpjslItlknZ/wjhCLrkzWCMZQYzg0+IovENkrkszfSNeGY8sHuLI7Ga615bRCh+37mpXLhVHNkJP1K3S2/zeauRIm2iB0LCq+F650Zkbalk0cEg1l7Sbr4KeOLadja0dCSxCu3HYRu6iyRq4YD+VK52WVfQtiQZLwDKcs7dfb6AcpLfMR23/bHVF6tsoCXJg0dPZibXjlKuso49+rn5IophM6BEIJ6+PKY0z7Sv/H6wpRtkEUV1yX7XzNrgqHfEb2be81xRZ0GUsYLPIpLYJ2DdMP7iSGy+mvMFIVpGc4vwcrfJDsiHNZm+YpmJ7lxCM1KTQfjBNiD1j+tW7F4PkkRFfcIk3UToKeZpAKKmCW7woM94q+9foy1w94nY2Ag9Yu5tEbRI/bkf7gW5inVE/WIBdxHrrWsdetazJWuDH7L/bAx59pYupyoQfojoXGCQEcMZCIJTPiI4kgBBrBDtE/HD7tZr1vYxWlNHBG11E/1TcqneoOhRmmTgmpeidIMKL+2POv8HbGKjmpdQpJH3pq/jRQoTg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
