travis:
  secure:
    BINSTAR_TOKEN: A+YVr4sc45Txky6NAmzN5k7eug0FmC3KTyOfbu2XS5QdQVp4nRw89J30bAN2tu/4fsijZ+QtgeeLV7U0ByxlrZKIq+X4TT7x82QREc2fBil8m0Rj2V5XKH9Yz/XDXZvVATCjxthbyBxS3cm/bv59WehRsKZJq0AiOIw0KwX3kSO3lSh1tSKL3mkfvyNZMyPT8MXV2Aq3jxvrpZlWzh+XCoggAy2Mn4adKV+4o/rQIlDegLh0shvjZ5bzoauYrtUkxr8YdlcTmlRn9wv2ei9etT6eb6sxog5qWKKBYYkzonizMg/MbTvFx3mjd2xmerU1i3RJSds6JZWOnk8HybAhdGlSbOSEZJhwOwM6SvbJdsMfbvLGddMfK67TplbF5sjYMGd6bhZJG0XSjLlB/XIIPXycDjTjqb64YidaU9fptKrUo7+X/IWHZlLSMrnEWqGtSqFbTrQx6/svnOkHEPf0xdNKLrB2am7heKHASJ835OZVLpv8nslYkqJOMVONsiV6QJ9OzyxElrxwFZNZmBVKeWimjc/EdbAGYGPN6rKpoCREoFtvTmJM8I7b/yMLjtn9YGD7QNZ7gsdi/7yaLnlR6qv3GoRcb0RsT5Z+YpNDkCzWA7W4YIkaLEyiQ2qIP5eP0ptBLJ0ONr967hpkoSKEKmpeIIuasoLwVZsk7OKQoPw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
