travis:
  secure:
    BINSTAR_TOKEN: pwp8IGjPEWK+FNOJR3PiP5Q7IPpzu/0JcQzIgkO8ltChewCGT9fraM4qupbWEM2ZBQm2I6FtRI3l8CroA+GpZgRPVdbVOC9Rual5Vwg5cf6f+u+9qSvsT5/S31ATbva+1GyH+K/OrIiclcPfLa1RFNGj5/uAhoLUIcriw5TzzE2pfF5WsGLAfd/qxhd/oK3FVrjK5ONhMZziaz3d0f4m1D980wRxhu4msJEpbZZjCZTnb1VF/8sxMObQ5s1exlLdeZGiyFo8gJBxGwotC+AZcsDois56iaBc+f/vbUBEYaK9YoWaJwrHi689pgtvFqVH95kLQ+X62aVCnLeXTFxgp3tBNUcc3JAAS6Ko+b9JbPfrou1MJLZQ3QMe19c6QBONY/YwCcnIEmPIjV63XSqIsgGmX77hac2NW4gTNl9dSF8OrTJocybWjc9fxSYx7hW2ZGmvODjnuuNR2g0aQsUqx90YtEatv3in1gRfBT12V/TswVfNpsVUy+RzYmHP397Bd+WDmUPECG9baXgWdCftj3iSratO/Whrplc1ThoerdC3qzf9KOzeWlxp77tqFIrlOSdM98+Qw9gSRbI88+ZwWLYbb0F74X9h+Q3036PR2AwEUlI9FFWtixVnR8HsXyia6nTWlrvRIQWo29PKUXF4KfXC7Epbh9Lv4hIlqQt3Sxo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
